server:
  port: 28080
# dubbo ����
dubbo:
  application:
    name: order-provider
  registry:
    address: zookeeper-sit.mid.io:2181
    protocol: zookeeper
    timeout: 10000
    register: false
  protocol:
    name: dubbo
    port: 20880