spring.application.name=test-demo
spring.application.group=com.alibaba.cloud.acm
alibaba.acm.endpoint=acm.aliyun.com
alibaba.acm.namespace=4a41ca48-b372-4514-b18b-0b229c2b53ba
alibaba.acm.accessKey=LTAI5tAaGudg55se4zMM7HQu
alibaba.acm.secretKey=Vv5jS7lvy7RCO4fEHvoVIjPmmRwvkL
