server:
  port: 38080
# dubbo �������
dubbo:
  application:
    name: user-consumer
  registry:
    address: zookeeper-sit.mid.io:2181
    protocol: zookeeper
    timeout: 10000
    check: false
  protocol:
    name: dubbo
    port: 20880