# 定义服务提供端口
server.port=8080

# 打印日志开关
retrofit.enable-log=true
# 是否启动熔断
retrofit.enable-degrade=false
# 配置连接池
retrofit.pool.test.keep-alive-second=3
retrofit.pool.test.max-idle-connections=100
# 禁用void返回值类型
retrofit.disable-void-return-type=true
# 日志打印拦截器
retrofit.logging-interceptor=com.github.lianjiatech.retrofit.spring.boot.interceptor.DefaultLoggingInterceptor
# 请求重试拦截器
retrofit.retry-interceptor=com.github.lianjiatech.retrofit.spring.boot.retry.DefaultRetryInterceptor
# 全局转换器工厂
retrofit.global-converter-factories=retrofit2.converter.jackson.JacksonConverterFactory
# 全局调用适配器工厂
retrofit.global-call-adapter-factories=com.github.lianjiatech.retrofit.spring.boot.core.BodyCallAdapterFactory,com.github.lianjiatech.retrofit.spring.boot.core.ResponseCallAdapterFactory
# 熔断降级实现方式
retrofit.degrade-type=sentinel
# 熔断资源名称解析器
retrofit.resource-name-parser=com.github.lianjiatech.retrofit.spring.boot.degrade.DefaultResourceNameParser