###RabbitMQ 使用
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=monco
spring.rabbitmq.password=monco
# 设置发送方确认机制
spring.rabbitmq.publisher-confirms=true
spring.rabbitmq.virtual-host=/
spring.rabbitmq.listener.simple.acknowledge-mode=auto